# Generated by Django 5.2.4 on 2025-07-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_doctors",
            field=models.BooleanField(
                default=False, help_text="Является ли пользователь врачем", verbose_name="Аккаунт врача"
            ),
        ),
    ]
