# Generated by Django 5.2.4 on 2025-07-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_doctors"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(
                blank=True, help_text="Введите отчество", max_length=100, null=True, verbose_name="Отчество"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, help_text="Введите имя", max_length=100, null=True, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, help_text="Введите фамилию", max_length=100, null=True, verbose_name="Фамилия"
            ),
        ),
    ]
