# Generated by Django 5.2.4 on 2025-07-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_surname_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_doctors",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Является ли пользователь врачем",
                null=True,
                verbose_name="Аккаунт врача",
            ),
        ),
    ]
