# Generated by Django 5.2.4 on 2025-07-07 18:30

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "appointment_date",
                    models.DateTimeField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=django.utils.timezone.now, message="Дата приема не может быть в прошлом"
                            )
                        ],
                        verbose_name="Дата и время приема",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждена"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус записи",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Дополнительные заметки")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания записи")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата последнего обновления")),
            ],
            options={
                "verbose_name": "Запись на прием",
                "verbose_name_plural": "Записи на прием",
                "ordering": ["-appointment_date"],
            },
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "address",
                    models.CharField(
                        help_text="Введите адрес компании", max_length=250, verbose_name="Адрес компании"
                    ),
                ),
                (
                    "phone_company",
                    models.CharField(
                        help_text="Введите телефон для связи", max_length=15, verbose_name="Телефон компании"
                    ),
                ),
                (
                    "head_physician",
                    models.CharField(
                        help_text="Введите ФИО главврача", max_length=250, verbose_name="ФИО главврача компании"
                    ),
                ),
                (
                    "email_company",
                    models.EmailField(
                        help_text="Введите электронную почту компании",
                        max_length=254,
                        unique=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "legal_entity",
                    models.CharField(
                        help_text="Юридическое лицо представляющее компанию",
                        max_length=250,
                        verbose_name="Юридичесок лицо",
                    ),
                ),
                (
                    "link_company",
                    models.URLField(blank=True, max_length=500, null=True, verbose_name="Ссылка на компанию"),
                ),
                (
                    "actual",
                    models.BooleanField(
                        default=True,
                        help_text="Действующая ли информация",
                        verbose_name="Актуальность контактной информации о компании",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name_content",
                    models.CharField(
                        help_text="Введите название контента", max_length=100, verbose_name="Название контента"
                    ),
                ),
                (
                    "text_content",
                    models.TextField(
                        blank=True, help_text="Введите текст контента", null=True, verbose_name="Текст контента"
                    ),
                ),
                (
                    "image_content",
                    models.ImageField(
                        blank=True, help_text="Загрузите нужную фотографию", null=True, upload_to="content/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контент",
                "verbose_name_plural": "Контент",
                "ordering": ["name_content"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosticResults",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_performed", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время проведения")),
                (
                    "result_file",
                    models.FileField(
                        upload_to="diagnostic_results/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png", "dicom"]
                            )
                        ],
                        verbose_name="Файл с результатами",
                    ),
                ),
                ("conclusion", models.TextField(blank=True, null=True, verbose_name="Заключение врача")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Дополнительные заметки")),
            ],
            options={
                "verbose_name": "Результат диагностики",
                "verbose_name_plural": "Результаты диагностики",
                "ordering": ["-date_performed"],
            },
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "first_name",
                    models.CharField(help_text="Введите имя врача", max_length=100, verbose_name="Имя врача"),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Введите фамилию врача", max_length=100, verbose_name="Фамилия врача"),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="Введите отчество врача", max_length=100, verbose_name="Отчество врача"
                    ),
                ),
                (
                    "photo_doctor",
                    models.ImageField(
                        blank=True, help_text="Загрузите нужную фотографию", null=True, upload_to="doctors/"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Введите текст", null=True, verbose_name="Текст описания о враче"
                    ),
                ),
                ("specialization", models.CharField(max_length=255, verbose_name="Специализация")),
                ("experience", models.PositiveIntegerField(default=0, verbose_name="Опыт работы (лет)")),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название услуги", max_length=200, verbose_name="Название услуги"
                    ),
                ),
                ("description", models.TextField(help_text="Введите описание услуги", verbose_name="Описание услуги")),
                ("price", models.IntegerField(verbose_name="Сумма оплаты за услугу")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, help_text="Загрузите нужную фотографию услуги", null=True, upload_to="services/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
