# Generated by Django 5.2.4 on 2025-07-07 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medical_diagnostic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticresults",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnostic_results",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticresults",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="medical_diagnostic.doctors",
                verbose_name="Врач",
            ),
        ),
        migrations.AddField(
            model_name="services",
            name="doctors",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="medical_diagnostic.doctors", verbose_name="Врач"
            ),
        ),
        migrations.AddField(
            model_name="diagnosticresults",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnostic_results",
                to="medical_diagnostic.services",
                verbose_name="Услуга",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="medical_diagnostic.services",
                verbose_name="Услуга",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(fields=("user", "appointment_date"), name="unique_user_appointment"),
        ),
    ]
