# Generated by Django 5.2.4 on 2025-07-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_diagnostic", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="latitude",
            field=models.FloatField(default=53.20429, verbose_name="Широта (координата Y)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contacts",
            name="longitude",
            field=models.FloatField(default=50.10946, verbose_name="Долгота (координата X)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contacts",
            name="address",
            field=models.TextField(help_text="Введите адрес компании", verbose_name="Адрес компании"),
        ),
    ]
