# Generated by Django 5.2.4 on 2025-07-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_diagnostic", "0003_contacts_latitude_contacts_longitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Телефон")),
                ("message", models.TextField(verbose_name="Сообщение")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата отправки")),
                ("is_processed", models.BooleanField(default=False, verbose_name="Обработано")),
            ],
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратные связи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="contacts",
            name="name",
            field=models.CharField(default="Diagnostic", max_length=250, verbose_name="Название компании"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="address",
            field=models.TextField(
                default="Diagnostic", help_text="Введите адрес компании", verbose_name="Адрес компании"
            ),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="email_company",
            field=models.EmailField(
                blank=True,
                help_text="Введите электронную почту компании",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Электронная почта",
            ),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="head_physician",
            field=models.CharField(
                blank=True,
                help_text="Введите ФИО главврача",
                max_length=250,
                null=True,
                verbose_name="ФИО главврача компании",
            ),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="legal_entity",
            field=models.CharField(
                blank=True,
                help_text="Юридическое лицо представляющее компанию",
                max_length=250,
                null=True,
                verbose_name="Юридичесок лицо",
            ),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="phone_company",
            field=models.CharField(
                blank=True,
                help_text="Введите телефон для связи",
                max_length=15,
                null=True,
                verbose_name="Телефон компании",
            ),
        ),
    ]
