# Generated by Django 5.2.4 on 2025-07-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_diagnostic", "0005_doctors_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctors",
            name="user",
        ),
    ]
