# Generated by Django 5.2.4 on 2025-07-12 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_diagnostic", "0006_remove_doctors_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="confirmation_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата подтверждения"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_doctors": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подтверждено врачом",
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="doctors",
            field=models.ForeignKey(
                limit_choices_to={"is_doctors": True},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Врач",
            ),
        ),
    ]
