# Generated by Django 5.2.4 on 2025-07-12 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_diagnostic", "0007_appointment_confirmation_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="confirmation_date",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="confirmed_by",
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                default=2,
                limit_choices_to={"is_doctors": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Врач",
            ),
            preserve_default=False,
        ),
    ]
