# Generated by Django 5.2.4 on 2025-07-12 19:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_diagnostic", "0008_remove_appointment_confirmation_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosticresults",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                default=1,
                limit_choices_to={"is_doctors": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_diagnostic",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Врач",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="diagnosticresults",
            name="result_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="diagnostic_results/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "dicom"]
                    )
                ],
                verbose_name="Файл с результатами",
            ),
        ),
    ]
