# Generated by Django 5.2.4 on 2025-07-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_diagnostic", "0009_alter_diagnosticresults_doctor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctors",
            name="education",
            field=models.TextField(
                blank=True,
                help_text="Введите название образовательного учреждения",
                null=True,
                verbose_name="Образовательное учреждение",
            ),
        ),
        migrations.AddField(
            model_name="doctors",
            name="qualification",
            field=models.TextField(
                blank=True,
                help_text="Введите названия курсов квалификации",
                null=True,
                verbose_name="Курсы квалификации",
            ),
        ),
        migrations.AddField(
            model_name="doctors",
            name="schedule",
            field=models.CharField(
                blank=True,
                help_text="Пример: Пн-Пт 9:00-18:00, Сб 10:00-15:00",
                max_length=255,
                verbose_name="Расписание",
            ),
        ),
    ]
