# Generated by Django 5.2.4 on 2025-07-16 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_diagnostic", "0011_alter_appointment_doctor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="doctors",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_doctors": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Врач",
            ),
        ),
    ]
